name: Tugas Akhir Deploy to AWS Beanstalk

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Generate Deployment package
        run: zip -r nodejs-app-build.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21

        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: movie-react
          environment_name: Movie-react-env
          version_label: ${{ github.sha }}
          region: ap-southeast-2
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-851725393473
          deployment_package: nodejs-app-build.zip
